---

- name: base configuration for all hosts
  hosts: NEW
  become: true

  vars:
    ansible_user: scott
    ansible_ssh_private_key_file: ~/.ssh/ansybull
 
  tasks:
    - include_tasks: tasks/update_packages.yml
    - include_tasks: tasks/base_config.yml
    - include_tasks: tasks/user_accounts.yml
    - include_role: name=install_packages

- name: install unifi controller 
  hosts: UNIFI
  become: true

  vars:
    ansible_user: scott

  tasks:
    - include_tasks: tasks/unifi-controller.yml