---

- name: configure servers
  hosts: all
  become: true

  vars:
   # ansible_user: scott

 
  tasks:
    - include_tasks: tasks/update_packages.yml
    - include_tasks: tasks/base_config.yml
    - include_tasks: tasks/user_accounts.yml
    - include_role: name=install_packages

