---

- hosts: all
  tags: always
  become: true
  tasks:
    - name: update packages (arch)
      pacman:
        update_cache: yes
        upgrade: yes
      when: ansible_distribution == "Archlinux"

    - name: update package cache (debian, etc)
      tags: always
      apt:
        update_cache: yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: update packages (debian etc)
      apt:
        upgrade: dist
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: remove useless packages from the cache (debian, etc)
      apt:
        autoclean: yes
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: remove dependencies that are no longer required (debian, etc)
      apt:
        autoremove: yes
      when: ansible_distribution in ["Debian", "Ubuntu"]
