---

# update app cache and upgrade all packages to latest

- name: Update app cache.
  package: update_cache=yes
  changed_when: false

- name: Install epel-release repository - RedHat only.
  package: 
    name: epel-release
    state: present
  when: ansible_os_family == 'RedHat'

- name: Upgrade all packages to the latest version.
  package:
    name: "*"
    state: latest  

- name: remove useless packages from the cache (debian, etc)
  apt:
    autoclean: yes
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: remove dependencies that are no longer required (debian, etc)
  apt:
    autoremove: yes
  when: ansible_distribution in ["Debian", "Ubuntu"]
