---

# Create and manage default user & group accounts

  - name: Include user account variables.
    include_vars: "../vars/account-vars.yml"

  - name: add specified groups.
    group:
      name: "{{ item }}"
      state: present
    loop: "{{ add_groups }}"
    when: add_groups | length > 0

  - name: create specified admin users - add to sudo or wheel group.
    user:
      name: "{{ item }}"
      shell: /bin/bash
      groups: "{{ sudo_group }}"
      append: true
    loop: "{{ admin_users }}"
    when: admin_users | length > 0

  - name: set home directory permissions to 700 for admin users.
    file:
      path: "/home/{{ item }}"
      state: directory
      mode: '0700'
    loop: "{{ admin_users }}"
    when: admin_users | length > 0

  - name: remove unwanted user accounts.
    user:
      name: "{{ item }}"
      state: absent
      remove: yes
    loop: "{{ remove_users }}"
    when: remove_users | length > 0
    
  - name: Copy ssh public key for admin users.
    authorized_key:
      user: "{{ item }}"
      state: present
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAWY9qDM5/3B9eMk/KCRJvJQRXkJu3c4CthAC2csLQMY ansybull deploy"
    loop: "{{ admin_users }}"
    when: admin_users | length > 0

  
