---
# tasks file for ansible_role_packages

- name: Include OS-specific app package variables.
  include_vars: "../vars/packages-{{ ansible_os_family }}.yml"

- name: Update Debian app cache if older than 1 hour.
  package: update_cache=yes cache_valid_time=3600
  when: ansible_os_family == 'Debian'

- name: Update RedHat app cache.
  package: update_cache=yes state=present
  when: ansible_os_family == 'RedHat'

- name: Install epel-release repository - RedHat only.
  package: 
    name: epel-release
    state: present
  when: ansible_os_family == 'RedHat'

- name: Upgrade all packages to the latest version.
  package:
    name: "*"
    state: latest  

- name: Make sure base packages are installed.
  package:
    name: "{{ my_packages }}"
    state: latest

- name: remove useless packages from the cache (debian, etc)
  apt:
    autoclean: yes
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: remove dependencies that are no longer required (debian, etc)
  apt:
    autoremove: yes
  when: ansible_distribution in ["Debian", "Ubuntu"]